/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA.CAJERO;
import java.awt.Color;
/**
 *
 * @author kimbe
 */
public class CAJERO_VJF extends javax.swing.JFrame {
 int xMouse, yMouse;
    /**
     * Creates new form CAJERO_VJF
     */
    public CAJERO_VJF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIDUSER1 = new javax.swing.JTextField();
        LABELADMINSTRADOR16 = new javax.swing.JLabel();
        LABELADMINSTRADOR17 = new javax.swing.JLabel();
        LABELADMINSTRADOR15 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        txtrol = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        header = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        LABELADMINSTRADOR1 = new javax.swing.JLabel();
        LABELADMINSTRADOR = new javax.swing.JLabel();
        LABELADMINSTRADOR8 = new javax.swing.JLabel();
        txtIDUSER = new javax.swing.JTextField();
        header1 = new javax.swing.JPanel();
        lbalelogo = new javax.swing.JLabel();
        LabelDash = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        header2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableMostrarResumen = new javax.swing.JTable();
        btnAgregarProducto = new javax.swing.JButton();
        cboProducto = new javax.swing.JComboBox<>();
        LABELADMINSTRADOR2 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        cboCliente = new javax.swing.JComboBox<>();
        btnagregarDNI = new javax.swing.JButton();
        btnVenta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        LABELADMINSTRADOR6 = new javax.swing.JLabel();
        LABELADMINSTRADOR5 = new javax.swing.JLabel();
        btnCalcularVuelto = new javax.swing.JButton();
        LABELADMINSTRADOR10 = new javax.swing.JLabel();
        txtIGV = new javax.swing.JTextField();
        LABELADMINSTRADOR11 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        LABELADMINSTRADOR12 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        txtVuelto = new javax.swing.JTextField();
        LABELADMINSTRADOR13 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        LABELADMINSTRADOR9 = new javax.swing.JLabel();
        LABELADMINSTRADOR3 = new javax.swing.JLabel();
        txtNameDni = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        LABELADMINSTRADOR14 = new javax.swing.JLabel();
        txtMonto1 = new javax.swing.JTextField();
        txtVuelto1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIDUSER1.setEditable(false);
        txtIDUSER1.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        getContentPane().add(txtIDUSER1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        LABELADMINSTRADOR16.setBackground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR16.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        LABELADMINSTRADOR16.setForeground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/placa-de-nombre.png"))); // NOI18N
        LABELADMINSTRADOR16.setText("NOMBRE");
        getContentPane().add(LABELADMINSTRADOR16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        LABELADMINSTRADOR17.setBackground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR17.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        LABELADMINSTRADOR17.setForeground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/placa-de-nombre.png"))); // NOI18N
        LABELADMINSTRADOR17.setText("CORREO");
        getContentPane().add(LABELADMINSTRADOR17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        LABELADMINSTRADOR15.setBackground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR15.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        LABELADMINSTRADOR15.setForeground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/placa-de-nombre.png"))); // NOI18N
        LABELADMINSTRADOR15.setText("ROL");
        getContentPane().add(LABELADMINSTRADOR15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, -1, -1));

        txtcorreo.setEditable(false);
        txtcorreo.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        getContentPane().add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 210, -1));

        txtrol.setEditable(false);
        txtrol.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        txtrol.setText("CAJERO");
        getContentPane().add(txtrol, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 210, -1));

        txtname.setEditable(false);
        txtname.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 210, -1));

        header.setBackground(new java.awt.Color(0, 74, 173));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        LABELADMINSTRADOR1.setBackground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        LABELADMINSTRADOR1.setForeground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/LogoAll -PEQ.png"))); // NOI18N
        LABELADMINSTRADOR1.setText("            CAJERO");

        LABELADMINSTRADOR.setBackground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        LABELADMINSTRADOR.setForeground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR.setText("FACTURACION");

        LABELADMINSTRADOR8.setBackground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR8.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        LABELADMINSTRADOR8.setForeground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/placa-de-nombre.png"))); // NOI18N
        LABELADMINSTRADOR8.setText("ID USER:");

        txtIDUSER.setEditable(false);
        txtIDUSER.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LABELADMINSTRADOR1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(LABELADMINSTRADOR8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIDUSER, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202)
                .addComponent(LABELADMINSTRADOR, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(804, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LABELADMINSTRADOR1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LABELADMINSTRADOR8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtIDUSER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LABELADMINSTRADOR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1900, 50));

        header1.setBackground(new java.awt.Color(0, 74, 173));
        header1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                header1MouseDragged(evt);
            }
        });
        header1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                header1MousePressed(evt);
            }
        });
        header1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbalelogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/LogoAll.png"))); // NOI18N
        header1.add(lbalelogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 170, 120));

        LabelDash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/POSTER1.png"))); // NOI18N
        header1.add(LabelDash, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 230, 470, 730));

        jLabel1.setText("-----------------------------------------------------------------");
        header1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 260, -1));

        getContentPane().add(header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, -1));

        header2.setBackground(new java.awt.Color(255, 255, 255));
        header2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                header2MouseDragged(evt);
            }
        });
        header2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                header2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout header2Layout = new javax.swing.GroupLayout(header2);
        header2.setLayout(header2Layout);
        header2Layout.setHorizontalGroup(
            header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        header2Layout.setVerticalGroup(
            header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );

        getContentPane().add(header2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 50, 230, 710));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtableMostrarResumen.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jtableMostrarResumen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID USUARIO", "NOMBRE Y APELLIDO", "CARGO", "CORREO", "ESTADO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtableMostrarResumen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableMostrarResumenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableMostrarResumen);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 1030, 300));

        btnAgregarProducto.setBackground(new java.awt.Color(204, 204, 204));
        btnAgregarProducto.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        btnAgregarProducto.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/menos.png"))); // NOI18N
        btnAgregarProducto.setText("AÑADIR");
        btnAgregarProducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnAgregarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 210, 110, 40));

        cboProducto.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        cboProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "ADMINISTRADOR", "PROVEDOR", "CAJERO" }));
        jPanel1.add(cboProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 230, 40));

        LABELADMINSTRADOR2.setBackground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR2.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        LABELADMINSTRADOR2.setForeground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/ID.png"))); // NOI18N
        LABELADMINSTRADOR2.setText("    CLIENTE :");
        jPanel1.add(LABELADMINSTRADOR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 210, 60));

        txtCantidad.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 210, 230, 40));

        cboCliente.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        cboCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "ADMINISTRADOR", "PROVEDOR", "CAJERO" }));
        jPanel1.add(cboCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 230, 40));

        btnagregarDNI.setBackground(new java.awt.Color(204, 204, 204));
        btnagregarDNI.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        btnagregarDNI.setForeground(new java.awt.Color(0, 0, 0));
        btnagregarDNI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/menos.png"))); // NOI18N
        btnagregarDNI.setText("AÑADIR");
        btnagregarDNI.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnagregarDNI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnagregarDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarDNIActionPerformed(evt);
            }
        });
        jPanel1.add(btnagregarDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 120, 110, 50));

        btnVenta.setBackground(new java.awt.Color(204, 204, 204));
        btnVenta.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        btnVenta.setForeground(new java.awt.Color(0, 0, 0));
        btnVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/editar-product.png"))); // NOI18N
        btnVenta.setText("REALIZAR VENTA");
        btnVenta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentaMouseClicked(evt);
            }
        });
        btnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaActionPerformed(evt);
            }
        });
        jPanel1.add(btnVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 820, 220, 60));

        jPanel2.setBackground(new java.awt.Color(0, 74, 173));
        jPanel2.setForeground(new java.awt.Color(0, 74, 173));

        LABELADMINSTRADOR6.setBackground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR6.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        LABELADMINSTRADOR6.setForeground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/placa-de-nombre.png"))); // NOI18N
        LABELADMINSTRADOR6.setText("      SUB TOTAL:   S/.");

        LABELADMINSTRADOR5.setBackground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR5.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        LABELADMINSTRADOR5.setForeground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/categorizacion.png"))); // NOI18N
        LABELADMINSTRADOR5.setText("           SUB TOTAL : ");

        btnCalcularVuelto.setBackground(new java.awt.Color(204, 204, 204));
        btnCalcularVuelto.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        btnCalcularVuelto.setForeground(new java.awt.Color(0, 0, 0));
        btnCalcularVuelto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/editar-product.png"))); // NOI18N
        btnCalcularVuelto.setText("CALCULAR VUELTO");
        btnCalcularVuelto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnCalcularVuelto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcularVuelto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalcularVueltoMouseClicked(evt);
            }
        });
        btnCalcularVuelto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularVueltoActionPerformed(evt);
            }
        });

        LABELADMINSTRADOR10.setBackground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR10.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        LABELADMINSTRADOR10.setForeground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/placa-de-nombre.png"))); // NOI18N
        LABELADMINSTRADOR10.setText("       IGV:             S/.");

        txtIGV.setEditable(false);
        txtIGV.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N

        LABELADMINSTRADOR11.setBackground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR11.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        LABELADMINSTRADOR11.setForeground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/placa-de-nombre.png"))); // NOI18N
        LABELADMINSTRADOR11.setText("      VUELTO :  ");

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N

        LABELADMINSTRADOR12.setBackground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR12.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        LABELADMINSTRADOR12.setForeground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/placa-de-nombre.png"))); // NOI18N
        LABELADMINSTRADOR12.setText("  INGRESAR MONTO");

        txtMonto.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N

        txtVuelto.setEditable(false);
        txtVuelto.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N

        LABELADMINSTRADOR13.setBackground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR13.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        LABELADMINSTRADOR13.setForeground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/placa-de-nombre.png"))); // NOI18N
        LABELADMINSTRADOR13.setText("       TOTAL :       S/.");

        txtSubTotal.setEditable(false);
        txtSubTotal.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCalcularVuelto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(LABELADMINSTRADOR5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(LABELADMINSTRADOR6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LABELADMINSTRADOR10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LABELADMINSTRADOR12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIGV, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LABELADMINSTRADOR11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LABELADMINSTRADOR13, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVuelto, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                        .addComponent(txtMonto)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(247, Short.MAX_VALUE)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(LABELADMINSTRADOR5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(LABELADMINSTRADOR6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LABELADMINSTRADOR10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIGV, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABELADMINSTRADOR13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABELADMINSTRADOR12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LABELADMINSTRADOR11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtVuelto)
                        .addGap(15, 15, 15)))
                .addComponent(btnCalcularVuelto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(188, 188, 188)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(370, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 370, 450, 610));

        LABELADMINSTRADOR9.setBackground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR9.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        LABELADMINSTRADOR9.setForeground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/placa-de-nombre.png"))); // NOI18N
        LABELADMINSTRADOR9.setText("    CANTIDAD :");
        jPanel1.add(LABELADMINSTRADOR9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 200, 60));

        LABELADMINSTRADOR3.setBackground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR3.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        LABELADMINSTRADOR3.setForeground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/categorizacion.png"))); // NOI18N
        LABELADMINSTRADOR3.setText("        RESUMEN");
        jPanel1.add(LABELADMINSTRADOR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 220, 60));

        txtNameDni.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        txtNameDni.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        jPanel1.add(txtNameDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 130, 230, 40));

        txtDNI.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        txtDNI.setBorder(javax.swing.BorderFactory.createTitledBorder("DNI"));
        jPanel1.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, 230, 40));

        LABELADMINSTRADOR14.setBackground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR14.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        LABELADMINSTRADOR14.setForeground(new java.awt.Color(255, 255, 255));
        LABELADMINSTRADOR14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/placa-de-nombre.png"))); // NOI18N
        LABELADMINSTRADOR14.setText("    PRODUCTO :");
        jPanel1.add(LABELADMINSTRADOR14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 200, 60));

        txtMonto1.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        jPanel1.add(txtMonto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtVuelto1.setEditable(false);
        txtVuelto1.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        jPanel1.add(txtVuelto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, -20, 1770, 990));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void header1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_header1MouseDragged

    private void header1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_header1MousePressed

    private void header2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header2MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_header2MouseDragged

    private void header2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_header2MousePressed

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentaMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnVentaMouseClicked

    private void btnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentaActionPerformed

    private void btnCalcularVueltoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularVueltoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnCalcularVueltoMouseClicked

    private void btnCalcularVueltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularVueltoActionPerformed
        // TODO addKKKur handling cHHHHHHDD||||¬¬¬»
    }//GEN-LAST:event_btnCalcularVueltoActionPerformed

    private void btnagregarDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnagregarDNIActionPerformed

    private void jtableMostrarResumenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableMostrarResumenMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtableMostrarResumenMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CAJERO_VJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CAJERO_VJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CAJERO_VJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CAJERO_VJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CAJERO_VJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LABELADMINSTRADOR;
    private javax.swing.JLabel LABELADMINSTRADOR1;
    private javax.swing.JLabel LABELADMINSTRADOR10;
    private javax.swing.JLabel LABELADMINSTRADOR11;
    private javax.swing.JLabel LABELADMINSTRADOR12;
    private javax.swing.JLabel LABELADMINSTRADOR13;
    private javax.swing.JLabel LABELADMINSTRADOR14;
    private javax.swing.JLabel LABELADMINSTRADOR15;
    private javax.swing.JLabel LABELADMINSTRADOR16;
    private javax.swing.JLabel LABELADMINSTRADOR17;
    private javax.swing.JLabel LABELADMINSTRADOR2;
    private javax.swing.JLabel LABELADMINSTRADOR3;
    private javax.swing.JLabel LABELADMINSTRADOR5;
    private javax.swing.JLabel LABELADMINSTRADOR6;
    private javax.swing.JLabel LABELADMINSTRADOR8;
    private javax.swing.JLabel LABELADMINSTRADOR9;
    private javax.swing.JLabel LabelDash;
    public javax.swing.JButton btnAgregarProducto;
    public javax.swing.JButton btnCalcularVuelto;
    public javax.swing.JButton btnVenta;
    public javax.swing.JButton btnagregarDNI;
    public javax.swing.JComboBox<String> cboCliente;
    public javax.swing.JComboBox<String> cboProducto;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JPanel header;
    private javax.swing.JPanel header1;
    private javax.swing.JPanel header2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jtableMostrarResumen;
    private javax.swing.JLabel lbalelogo;
    public javax.swing.JTextField txtCantidad;
    public javax.swing.JTextField txtDNI;
    public javax.swing.JTextField txtIDUSER;
    public javax.swing.JTextField txtIDUSER1;
    public javax.swing.JTextField txtIGV;
    public javax.swing.JTextField txtMonto;
    public javax.swing.JTextField txtMonto1;
    public javax.swing.JTextField txtNameDni;
    public javax.swing.JTextField txtSubTotal;
    public javax.swing.JTextField txtTotal;
    public javax.swing.JTextField txtVuelto;
    public javax.swing.JTextField txtVuelto1;
    public javax.swing.JTextField txtcorreo;
    public javax.swing.JTextField txtname;
    public javax.swing.JTextField txtrol;
    // End of variables declaration//GEN-END:variables
}
